services:

  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}
    restart: unless-stopped

    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_USER=${DB_USER}

    ports:
    - "${DB_PORT}:5432"

    volumes:
    - odoo-db-data:/var/lib/postgresql/data
  
  odoo:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE}
    restart: unless-stopped

    depends_on:
    - db

    ports:
    - "${WEB_PORT}:8069"

    volumes:
    - ./config:/etc/odoo
    - ./addons:/mnt/extra-addons

    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"

volumes:
  odoo-db-data: